# Site settings
title: "Aakash Bogati"
author: "Aakash Bogati"
description: "Developer sharing real coding adventures, insights, and solutions. From coffee to code, one line at a time."
email: "your-email@example.com"

# Theme - IMPORTANT: This must be exactly right
theme: minima

# CORRECTED URLs for your project pages setup
url: "https://akbogati123.github.io"
baseurl: "/AakashBogati.github.io"

# Social links (update with your real handles)
github_username: AKBogati123
linkedin_username: your-linkedin-username
twitter_username: your-twitter-handle

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"
  
# Show excerpts on homepage
show_excerpts: true

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Collections (if you want to add more content types)
collections:
  projects:
    output: true
    permalink: /:collection/:name/
header_pages:
  - blog.md
  - about.md
# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Aakash Bogati"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
