# Site settings
title: "Aakash Bogati"
author: "Aakash Bogati"
description: "Full-Stack Developer & Technical Writer sharing real development experiences, practical tutorials, and insights from the world of software engineering."
email: "your-email@example.com"

# Theme
theme: minima

# URLs
url: "https://akbogati123.github.io"
baseurl: "/AakashBogati.github.io"

# Social links
github_username: AKBogati123
linkedin_username: your-linkedin-username
twitter_username: your-twitter-handle

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Show excerpts
show_excerpts: true

# Pagination
paginate: 12
paginate_path: "/page:num/"

# Header navigation
header_pages:
  - blog.md
  - about.md

# Post defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Aakash Bogati"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
